/**
 * Exam catalogue - the backbone of the site (Exams page, exam detail pages,
 * Eligibility Finder, enquiry dropdown, standards tables).
 *
 * Mirrors the `exams` table (supabase/migrations/0004). These defaults render
 * until the CMS table has rows; supabase/seed/exams.sql seeds the same data so
 * the admin can edit it.
 *
 * ACCURACY: figures are indicative, based on recent notifications. Age bands,
 * qualifications and patterns change between cycles. Verify each row against
 * the current official notification before launch and every cycle after.
 * Fields we could not verify are left blank rather than guessed.
 */

export type Vertical = "armed-forces" | "capf" | "odisha" | "railways" | "ssc" | "officer";

export const VERTICALS: { key: Vertical; label: string; short: string }[] = [
  { key: "armed-forces", label: "Army, Navy and Air Force", short: "Armed Forces" },
  { key: "capf", label: "Central Armed Police Forces", short: "CAPF" },
  { key: "odisha", label: "Odisha State", short: "Odisha State" },
  { key: "railways", label: "Railways", short: "Railways" },
  { key: "ssc", label: "Bank, SSC and central government", short: "Bank and SSC" },
  { key: "officer", label: "Officer entries", short: "Officer" },
];

export const verticalLabel = (v: string) => VERTICALS.find((x) => x.key === v)?.short ?? v;

export type ExamGender = "male" | "female" | "both";

export type Exam = {
  id?: string;
  slug: string;
  name: string;
  short_name: string;
  vertical: Vertical;
  force: string;
  stage: string;
  qualification: string;
  age_min: number | null;
  age_max: number | null;
  gender: ExamGender;
  marital_status: string;
  domicile: string;
  intro: string;
  pattern: string;
  syllabus: string;
  salary: string;
  stages: string[];
  notification_month: string;
  exam_month: string;
  official_url: string;
  banner_path: string;
  sort_order: number;
};

/** Education levels, lowest to highest. Used by the Eligibility Finder. */
export type Education = "8th" | "10th" | "12th-science" | "12th-other" | "iti-diploma" | "graduate";

const base = {
  marital_status: "",
  domicile: "All India",
  salary: "",
  notification_month: "",
  exam_month: "",
  banner_path: "",
};

const ARMY_STAGES = ["APPLY", "CBT", "PST", "PET", "DV", "MED", "MERIT"];
const CAPF_STAGES = ["APPLY", "CBT", "PST", "PET", "DV", "MED", "MERIT"];

export const EXAMS: Exam[] = [
  // ── Armed Forces ─────────────────────────────────────────────
  {
    ...base,
    slug: "army-agniveer-gd",
    name: "Army Agniveer General Duty",
    short_name: "Agniveer GD",
    vertical: "armed-forces",
    force: "Indian Army",
    stage: "After 10th",
    qualification: "Class 10 with 45% aggregate and 33% in each subject",
    age_min: 17,
    age_max: 21,
    gender: "male",
    marital_status: "Unmarried",
    intro:
      "<p>The largest recruitment in the country. Candidates clear an online Common Entrance Exam, then a recruitment rally where running, beam and ditch decide the merit.</p>",
    pattern:
      "<p>Online CEE: 50 questions, 100 marks, 60 minutes, covering general knowledge, science, maths and logical reasoning. Negative marking applies.</p>",
    syllabus: "<p>Class 10 level maths and science, general knowledge, current affairs and reasoning.</p>",
    stages: ARMY_STAGES,
    official_url: "https://joinindianarmy.nic.in",
    sort_order: 1,
  },
  {
    ...base,
    slug: "army-agniveer-technical",
    name: "Army Agniveer Technical",
    short_name: "Agniveer Tech",
    vertical: "armed-forces",
    force: "Indian Army",
    stage: "After 12th",
    qualification: "Class 12 science (Physics, Chemistry, Maths, English) with 50% aggregate",
    age_min: 17,
    age_max: 21,
    gender: "male",
    marital_status: "Unmarried",
    intro: "<p>Technical trades in the Army. The written exam goes deeper into physics, chemistry and maths than the GD paper.</p>",
    pattern: "<p>Online CEE on physics, chemistry, maths and general knowledge, followed by the recruitment rally.</p>",
    syllabus: "<p>Class 11 and 12 physics, chemistry and maths, general knowledge.</p>",
    stages: ARMY_STAGES,
    official_url: "https://joinindianarmy.nic.in",
    sort_order: 2,
  },
  {
    ...base,
    slug: "army-agniveer-clerk",
    name: "Army Agniveer Clerk / Store Keeper Technical",
    short_name: "Agniveer Clerk",
    vertical: "armed-forces",
    force: "Indian Army",
    stage: "After 12th",
    qualification: "Class 12 in any stream with 60% aggregate and 50% in each subject",
    age_min: 17,
    age_max: 21,
    gender: "male",
    marital_status: "Unmarried",
    intro: "<p>Clerical and store-keeping trades. English and computer awareness carry more weight here than in GD.</p>",
    pattern: "<p>Online CEE on general knowledge, science, maths, computer science and English.</p>",
    syllabus: "<p>General knowledge, basic science and maths, English grammar and comprehension, computer basics.</p>",
    stages: ARMY_STAGES,
    official_url: "https://joinindianarmy.nic.in",
    sort_order: 3,
  },
  {
    ...base,
    slug: "army-agniveer-tradesman",
    name: "Army Agniveer Tradesman",
    short_name: "Agniveer Tradesman",
    vertical: "armed-forces",
    force: "Indian Army",
    stage: "After 8th or 10th",
    qualification: "Class 8 or Class 10 pass, depending on trade",
    age_min: 17,
    age_max: 21,
    gender: "male",
    marital_status: "Unmarried",
    intro: "<p>Trades such as cook, washerman, tailor and support staff. The written exam is shorter; the rally is the same.</p>",
    pattern: "<p>Online CEE on general knowledge, maths and reasoning at Class 8 or Class 10 level.</p>",
    syllabus: "<p>Basic maths, general knowledge and reasoning.</p>",
    stages: ARMY_STAGES,
    official_url: "https://joinindianarmy.nic.in",
    sort_order: 4,
  },
  {
    ...base,
    slug: "navy-agniveer-ssr",
    name: "Navy Agniveer SSR",
    short_name: "Navy SSR",
    vertical: "armed-forces",
    force: "Indian Navy",
    stage: "After 12th",
    qualification: "Class 12 with Maths and Physics plus Chemistry, Biology or Computer Science",
    age_min: 17,
    age_max: 21,
    gender: "both",
    marital_status: "Unmarried",
    intro: "<p>Senior Secondary Recruit. Sailors train at INS Chilka in Odisha, which makes this one of the most sought-after entries in the state.</p>",
    pattern: "<p>Computer-based test on English, science, maths and general awareness, followed by a physical fitness test and medical.</p>",
    syllabus: "<p>Class 12 level maths and science, English and general awareness.</p>",
    stages: ["APPLY", "CBT", "PET", "MED", "MERIT"],
    official_url: "https://www.joinindiannavy.gov.in",
    sort_order: 5,
  },
  {
    ...base,
    slug: "navy-agniveer-mr",
    name: "Navy Agniveer MR",
    short_name: "Navy MR",
    vertical: "armed-forces",
    force: "Indian Navy",
    stage: "After 10th",
    qualification: "Class 10 pass",
    age_min: 17,
    age_max: 21,
    gender: "both",
    marital_status: "Unmarried",
    intro: "<p>Matric Recruit for roles such as chef, steward and hygienist. Training is at INS Chilka.</p>",
    pattern: "<p>Computer-based test at Class 10 level on science, maths and general awareness, then physical fitness test and medical.</p>",
    syllabus: "<p>Class 10 science and maths, general awareness.</p>",
    stages: ["APPLY", "CBT", "PET", "MED", "MERIT"],
    official_url: "https://www.joinindiannavy.gov.in",
    sort_order: 6,
  },
  {
    ...base,
    slug: "airforce-agniveervayu-x",
    name: "Air Force Agniveervayu (Science, X group)",
    short_name: "Airman X",
    vertical: "armed-forces",
    force: "Indian Air Force",
    stage: "After 12th",
    qualification: "Class 12 with Physics, Maths and English (50% aggregate and 50% in English), or a 3-year engineering diploma",
    age_min: 17,
    age_max: 21,
    gender: "both",
    marital_status: "Unmarried",
    intro: "<p>Technical airman trades. The science paper tests physics and maths at Class 12 level.</p>",
    pattern: "<p>Online test on English, physics and maths, then physical fitness test, adaptability test and medical.</p>",
    syllabus: "<p>Class 11 and 12 physics and maths, English.</p>",
    stages: ["APPLY", "CBT", "PET", "MED", "MERIT"],
    official_url: "https://agnipathvayu.cdac.in",
    sort_order: 7,
  },
  {
    ...base,
    slug: "airforce-agniveervayu-y",
    name: "Air Force Agniveervayu (Non-science, Y group)",
    short_name: "Airman Y",
    vertical: "armed-forces",
    force: "Indian Air Force",
    stage: "After 12th",
    qualification: "Class 12 in any stream with 50% aggregate and 50% in English",
    age_min: 17,
    age_max: 21,
    gender: "both",
    marital_status: "Unmarried",
    intro: "<p>Non-technical airman trades, open to arts and commerce students.</p>",
    pattern: "<p>Online test on English and reasoning and general awareness, then physical fitness test, adaptability test and medical.</p>",
    syllabus: "<p>English, reasoning and general awareness.</p>",
    stages: ["APPLY", "CBT", "PET", "MED", "MERIT"],
    official_url: "https://agnipathvayu.cdac.in",
    sort_order: 8,
  },
  {
    ...base,
    slug: "coast-guard-navik",
    name: "Coast Guard Navik and Yantrik",
    short_name: "ICG Navik",
    vertical: "armed-forces",
    force: "Indian Coast Guard",
    stage: "After 10th or 12th",
    qualification: "Navik GD: Class 12 with Maths and Physics. Navik DB: Class 10. Yantrik: Class 10 plus diploma.",
    age_min: 18,
    age_max: 22,
    gender: "male",
    intro: "<p>Sailor-level entries into the Coast Guard, with a staged online exam, physical fitness test and medical.</p>",
    pattern: "<p>Multi-stage computer-based exam, followed by assessment, physical fitness test and medical.</p>",
    syllabus: "<p>Maths, science, English, reasoning and general knowledge at the entry's level.</p>",
    stages: ["APPLY", "CBT", "PET", "DV", "MED", "MERIT"],
    official_url: "https://joinindiancoastguard.cdac.in",
    sort_order: 9,
  },

  // ── CAPF ─────────────────────────────────────────────────────
  {
    ...base,
    slug: "ssc-gd-constable",
    name: "SSC GD Constable",
    short_name: "SSC GD",
    vertical: "capf",
    force: "BSF, CISF, CRPF, ITBP, SSB, Assam Rifles, NCB, SSF",
    stage: "After 10th",
    qualification: "Class 10 pass",
    age_min: 18,
    age_max: 23,
    gender: "both",
    intro: "<p>One exam, eight forces. The CBT shortlists candidates for a physical test where the 5 km run (men) and 1.6 km run (women) decide who goes forward.</p>",
    pattern: "<p>CBT: 80 questions, 160 marks, 60 minutes. Reasoning, general knowledge, elementary maths and English or Hindi, 20 questions each. Negative marking applies.</p>",
    syllabus: "<p>Reasoning, general awareness, elementary maths and English or Hindi at Class 10 level.</p>",
    stages: CAPF_STAGES,
    official_url: "https://ssc.gov.in",
    sort_order: 10,
  },
  {
    ...base,
    slug: "ssc-cpo",
    name: "SSC CPO Sub-Inspector",
    short_name: "SSC CPO",
    vertical: "capf",
    force: "Delhi Police and CAPF",
    stage: "After graduation",
    qualification: "Graduation in any discipline",
    age_min: 20,
    age_max: 25,
    gender: "both",
    intro: "<p>Sub-Inspector posts in Delhi Police and the CAPFs. Two written papers with a physical test in between.</p>",
    pattern: "<p>Paper 1 CBT, physical standard and endurance test, Paper 2 on English, then medical.</p>",
    syllabus: "<p>Reasoning, general knowledge, quantitative aptitude, English comprehension.</p>",
    stages: CAPF_STAGES,
    official_url: "https://ssc.gov.in",
    sort_order: 11,
  },

  // ── Odisha State ─────────────────────────────────────────────
  {
    ...base,
    slug: "odisha-police-constable",
    name: "Odisha Police Constable",
    short_name: "OP Constable",
    vertical: "odisha",
    force: "Odisha Police (OUSSSC)",
    stage: "After 12th",
    qualification: "Plus Two (Class 12) pass. Must read, write and speak Odia.",
    age_min: 18,
    age_max: 23,
    gender: "both",
    domicile: "Odisha",
    intro: "<p>Recruited by the Odisha Uniformed Services Staff Selection Commission (OUSSSC), which now handles recruitment to the state's uniformed services. Odia language, Odisha GK and the physical test all carry real weight.</p>",
    pattern: "<p>Written exam on general knowledge, reasoning, arithmetic, Odia and English, followed by physical tests and document verification. Confirm the exact pattern in the current OUSSSC notification.</p>",
    syllabus: "<p>Odisha GK, general knowledge, reasoning, arithmetic, Odia and English.</p>",
    stages: CAPF_STAGES,
    official_url: "https://ousssc.odisha.gov.in",
    sort_order: 12,
  },
  {
    ...base,
    slug: "odisha-police-si",
    name: "Odisha Police Sub-Inspector",
    short_name: "OP SI",
    vertical: "odisha",
    force: "Odisha Police",
    stage: "After graduation",
    qualification: "Graduation. Must read, write and speak Odia.",
    age_min: 21,
    age_max: 25,
    gender: "both",
    domicile: "Odisha",
    intro: "<p>Sub-Inspector of Police in Odisha. A tougher written exam and the same emphasis on the physical test.</p>",
    pattern: "<p>Written exam, physical tests and interview or document verification. Confirm the exact pattern in the current notification.</p>",
    syllabus: "<p>General studies, reasoning, maths, Odia and English.</p>",
    stages: CAPF_STAGES,
    official_url: "https://ousssc.odisha.gov.in",
    sort_order: 13,
  },
  {
    ...base,
    slug: "odisha-forest-guard",
    name: "Odisha Forest Guard and Forester",
    short_name: "Forest Guard",
    vertical: "odisha",
    force: "Forest Department, Odisha (OSSSC)",
    stage: "After 10th or 12th",
    qualification: "Class 10 for Forest Guard, Class 12 for Forester (confirm in notification)",
    age_min: 18,
    age_max: null,
    gender: "both",
    domicile: "Odisha",
    intro: "<p>Field posts in the Odisha Forest Department, recruited through OSSSC with a walking or running test.</p>",
    pattern: "<p>Written exam followed by a physical test. Confirm the pattern in the current OSSSC notification.</p>",
    syllabus: "<p>General knowledge, Odisha GK, arithmetic, Odia and English.</p>",
    stages: ["APPLY", "CBT", "PET", "DV", "MERIT"],
    official_url: "https://www.osssc.gov.in",
    sort_order: 14,
  },

  {
    ...base,
    slug: "opsc-ocs",
    name: "OPSC Odisha Civil Services",
    short_name: "OPSC OCS",
    vertical: "odisha",
    force: "Odisha Public Service Commission",
    stage: "After graduation",
    qualification: "Graduation from a recognised university. Must read, write and speak Odia.",
    age_min: 21,
    age_max: null,
    gender: "both",
    domicile: "Odisha",
    intro: "<p>The Odisha Civil Services examination recruits officers to the Odisha Administrative Service, Odisha Police Service and allied state services.</p>",
    pattern: "<p>Preliminary exam (objective, General Studies and a qualifying aptitude paper), Main exam (descriptive) and a personality test. Confirm the pattern and the upper age limit in the current OPSC notification.</p>",
    syllabus: "<p>General studies, Odisha history, geography and economy, polity, current affairs, aptitude, Odia and English.</p>",
    stages: ["APPLY", "CBT", "DV", "MERIT"],
    official_url: "https://www.opsc.gov.in",
    sort_order: 15,
  },
  {
    ...base,
    slug: "opsc-aso",
    name: "OPSC Assistant Section Officer (ASO)",
    short_name: "OPSC ASO",
    vertical: "odisha",
    force: "Odisha Secretariat (OPSC)",
    stage: "After graduation",
    qualification: "Graduation. Must read, write and speak Odia; computer knowledge required.",
    age_min: 21,
    age_max: null,
    gender: "both",
    domicile: "Odisha",
    intro: "<p>Assistant Section Officer posts in the Odisha Secretariat and OPSC. A desk post with a written exam and a computer skill test, no physical test.</p>",
    pattern: "<p>Written examination followed by a computer skill test. Confirm the exact pattern and the upper age limit in the current OPSC notification.</p>",
    syllabus: "<p>General studies, Odisha GK, reasoning, arithmetic, Odia, English and computer basics.</p>",
    stages: ["APPLY", "CBT", "DV", "MERIT"],
    official_url: "https://www.opsc.gov.in",
    sort_order: 16,
  },
  {
    ...base,
    slug: "ossc-osssc",
    name: "OSSC and OSSSC Recruitment",
    short_name: "OSSC / OSSSC",
    vertical: "odisha",
    force: "Odisha Staff Selection Commission and Odisha Subordinate Staff Selection Commission",
    stage: "After 10th, 12th or graduation",
    qualification: "Depends on the post: Class 10, Class 12 or graduation. Must read, write and speak Odia.",
    age_min: 18,
    age_max: null,
    gender: "both",
    domicile: "Odisha",
    intro: "<p>Group B and C posts across Odisha government departments: combined recruitment exams, revenue and field posts, clerical and technical posts.</p>",
    pattern: "<p>Preliminary and main written exams for most posts, with a skill or physical test for some. Confirm the pattern in the current OSSC or OSSSC notification.</p>",
    syllabus: "<p>Odisha GK, general knowledge, reasoning, arithmetic, Odia, English and computer basics.</p>",
    stages: ["APPLY", "CBT", "DV", "MERIT"],
    official_url: "https://www.ossc.gov.in",
    sort_order: 17,
  },

  // ── Railways ─────────────────────────────────────────────────
  {
    ...base,
    slug: "rrb-group-d",
    name: "RRB Group D",
    short_name: "Group D",
    vertical: "railways",
    force: "Indian Railways",
    stage: "After 10th",
    qualification: "Class 10 or ITI",
    age_min: 18,
    age_max: 36,
    gender: "both",
    intro: "<p>Level 1 posts across Indian Railways. The physical test is a weighted carry and a timed 1000 m run.</p>",
    pattern: "<p>CBT: 100 questions, 90 minutes. General science, maths, reasoning and general awareness. Negative marking of one third.</p>",
    syllabus: "<p>Class 10 science and maths, reasoning, general awareness and current affairs.</p>",
    stages: ["APPLY", "CBT", "PET", "DV", "MED", "MERIT"],
    official_url: "https://indianrailways.gov.in",
    sort_order: 18,
  },
  {
    ...base,
    slug: "rrb-ntpc",
    name: "RRB NTPC",
    short_name: "NTPC",
    vertical: "railways",
    force: "Indian Railways",
    stage: "After 12th or graduation",
    qualification: "Class 12 for undergraduate posts, graduation for graduate posts",
    age_min: 18,
    age_max: 36,
    gender: "both",
    intro: "<p>Non-technical popular categories such as clerk, station master and goods guard. No physical test for most posts.</p>",
    pattern: "<p>Two CBT stages, then a typing or aptitude test depending on the post.</p>",
    syllabus: "<p>Maths, reasoning and general awareness.</p>",
    stages: ["APPLY", "CBT", "DV", "MED", "MERIT"],
    official_url: "https://indianrailways.gov.in",
    sort_order: 19,
  },
  {
    ...base,
    slug: "rrb-alp",
    name: "RRB Assistant Loco Pilot and Technician",
    short_name: "ALP",
    vertical: "railways",
    force: "Indian Railways",
    stage: "After 10th plus ITI or diploma",
    qualification: "Class 10 with ITI, or a diploma or degree in engineering",
    age_min: 18,
    age_max: 33,
    gender: "both",
    intro: "<p>Loco pilot and technical posts. The second CBT includes a trade paper and ALP candidates sit a computer-based aptitude test.</p>",
    pattern: "<p>CBT 1, CBT 2 (including trade), computer-based aptitude test for ALP.</p>",
    syllabus: "<p>Maths, reasoning, general science, general awareness and trade-specific topics.</p>",
    stages: ["APPLY", "CBT", "DV", "MED", "MERIT"],
    official_url: "https://indianrailways.gov.in",
    sort_order: 20,
  },
  {
    ...base,
    slug: "rpf-constable",
    name: "RPF Constable",
    short_name: "RPF Constable",
    vertical: "railways",
    force: "Railway Protection Force",
    stage: "After 10th",
    qualification: "Class 10 pass",
    age_min: 18,
    age_max: 28,
    gender: "both",
    intro: "<p>Constable in the Railway Protection Force. A CBT followed by a physical test with run, long jump and high jump.</p>",
    pattern: "<p>CBT on general awareness, arithmetic and reasoning, then physical efficiency and measurement tests.</p>",
    syllabus: "<p>General awareness, arithmetic, general intelligence and reasoning.</p>",
    stages: CAPF_STAGES,
    official_url: "https://indianrailways.gov.in",
    sort_order: 21,
  },

  // ── SSC and central government ───────────────────────────────
  {
    ...base,
    slug: "ssc-mts",
    name: "SSC MTS and Havaldar",
    short_name: "SSC MTS",
    vertical: "ssc",
    force: "Central government departments",
    stage: "After 10th",
    qualification: "Class 10 pass",
    age_min: 18,
    age_max: 27,
    gender: "both",
    intro: "<p>Multi-tasking staff posts. Havaldar candidates also face a physical test.</p>",
    pattern: "<p>CBT in two sessions: numerical and reasoning, then general awareness and English.</p>",
    syllabus: "<p>Reasoning, maths, general awareness and English at Class 10 level.</p>",
    stages: ["APPLY", "CBT", "PET", "DV", "MERIT"],
    official_url: "https://ssc.gov.in",
    sort_order: 22,
  },
  {
    ...base,
    slug: "ssc-chsl-cgl",
    name: "SSC CHSL and CGL",
    short_name: "CHSL / CGL",
    vertical: "ssc",
    force: "Central government departments",
    stage: "After 12th or graduation",
    qualification: "Class 12 for CHSL, graduation for CGL",
    age_min: 18,
    age_max: 32,
    gender: "both",
    intro: "<p>Clerical and officer-level desk posts across central ministries. No physical test.</p>",
    pattern: "<p>Tier 1 and Tier 2 CBTs, with skill or typing tests depending on the post.</p>",
    syllabus: "<p>Quantitative aptitude, reasoning, English and general awareness.</p>",
    stages: ["APPLY", "CBT", "DV", "MERIT"],
    official_url: "https://ssc.gov.in",
    sort_order: 23,
  },

  {
    ...base,
    slug: "bank-po",
    name: "Bank PO (IBPS and SBI)",
    short_name: "Bank PO",
    vertical: "ssc",
    force: "Public sector banks",
    stage: "After graduation",
    qualification: "Graduation in any discipline",
    age_min: 20,
    age_max: 30,
    gender: "both",
    intro: "<p>Probationary Officer posts in public sector banks, recruited through IBPS and SBI. No physical test.</p>",
    pattern: "<p>Online preliminary exam (English, quantitative aptitude, reasoning), online main exam, then an interview. Confirm details in the current IBPS or SBI notification.</p>",
    syllabus: "<p>Quantitative aptitude, reasoning, English, banking and general awareness, computer knowledge.</p>",
    stages: ["APPLY", "CBT", "DV", "MERIT"],
    official_url: "https://www.ibps.in",
    sort_order: 24,
  },
  {
    ...base,
    slug: "bank-clerk",
    name: "Bank Clerk (IBPS and SBI)",
    short_name: "Bank Clerk",
    vertical: "ssc",
    force: "Public sector banks",
    stage: "After graduation",
    qualification: "Graduation in any discipline. Proficiency in the official language of the state applied for.",
    age_min: 20,
    age_max: 28,
    gender: "both",
    intro: "<p>Clerical (customer service associate) posts in public sector banks through IBPS Clerk and SBI Junior Associate. No physical test and no interview.</p>",
    pattern: "<p>Online preliminary and main exams, then a local language proficiency test. Confirm details in the current IBPS or SBI notification.</p>",
    syllabus: "<p>Quantitative aptitude, reasoning, English, general and financial awareness, computer knowledge.</p>",
    stages: ["APPLY", "CBT", "DV", "MERIT"],
    official_url: "https://www.ibps.in",
    sort_order: 25,
  },

  // ── Officer entries ──────────────────────────────────────────
  {
    ...base,
    slug: "nda",
    name: "NDA and NA",
    short_name: "NDA",
    vertical: "officer",
    force: "Army, Navy and Air Force",
    stage: "After 12th",
    qualification: "Class 12 (Physics and Maths for Air Force and Navy wings)",
    age_min: 16,
    age_max: 19,
    gender: "both",
    marital_status: "Unmarried",
    intro: "<p>Officer entry straight after school. UPSC written exam, then the five-day SSB interview.</p>",
    pattern: "<p>UPSC written: Maths and General Ability Test, followed by the SSB interview and medical.</p>",
    syllabus: "<p>Class 11 and 12 maths, English, general knowledge and science.</p>",
    stages: ["APPLY", "CBT", "MED", "MERIT"],
    official_url: "https://upsc.gov.in",
    sort_order: 26,
  },
  {
    ...base,
    slug: "cds-afcat",
    name: "CDS and AFCAT",
    short_name: "CDS / AFCAT",
    vertical: "officer",
    force: "Army, Navy and Air Force",
    stage: "After graduation",
    qualification: "Graduation (branch-specific requirements apply)",
    age_min: 19,
    age_max: 26,
    gender: "both",
    marital_status: "Unmarried",
    intro: "<p>Graduate officer entries. Written exam followed by the SSB or AFSB interview.</p>",
    pattern: "<p>CDS: English, GK and maths (UPSC). AFCAT: online test on verbal, numerical, reasoning and GK.</p>",
    syllabus: "<p>English, general knowledge, elementary maths, reasoning.</p>",
    stages: ["APPLY", "CBT", "MED", "MERIT"],
    official_url: "https://upsc.gov.in",
    sort_order: 27,
  },
];

export const examBySlug = (slug: string) => EXAMS.find((e) => e.slug === slug);

/** Journey stage codes, for mapping exam.stages to the 7-stage journey. */
export const STAGE_LABELS: Record<string, string> = {
  APPLY: "Application",
  CBT: "Written exam",
  PST: "Physical standard test",
  PET: "Physical efficiency test",
  DV: "Document verification",
  MED: "Medical",
  MERIT: "Merit and joining",
};
