/** SEO defaults per page (client-safe plain data). Overridable in Admin -> SEO. */
export type SeoPage = { key: string; label: string; path: string; absolute?: boolean; title: string; description: string };

export const SEO_PAGES: SeoPage[] = [
  { key: "home", label: "Home", path: "/", absolute: true,
    title: "Samantroy Academy, Berhampur | Defence, Police, Bank and SSC Coaching",
    description: "Defence coaching in Brahmapur (Berhampur), Ganjam since 2001. 4000+ recruitments in Army, Navy, Air Force, CAPF, Odisha Police, OSSC, OPSC, Bank, Railway and SSC." },
  { key: "about", label: "About", path: "/about",
    title: "About Samantroy Academy, Brahmapur: Since 2001",
    description: "Samantroy Academy for Defence Career Studies has coached aspirants in Brahmapur (Berhampur), Ganjam since 2001: 4000+ recruitments into defence and government jobs." },
  { key: "recruitment-process", label: "Recruitment Process", path: "/recruitment-process",
    title: "Recruitment Process: Application to Joining in Seven Stages",
    description: "How Army, Navy, Air Force, SSC GD, Odisha Police and railway recruitment works: application, written exam, PST, PET, documents, medical and merit list." },
  { key: "exams", label: "Exams", path: "/exams",
    title: "Defence and Government Exams After 10th, +2 and Graduation",
    description: "Exams we coach for: Army GD, Navy SSR and MR, Air Force X and Y, BSF, CRPF, CISF, SSB, Odisha Police, OSSC, OPSC, Bank PO, RRB, SSC CGL, NDA and CDS." },
  { key: "standards", label: "Physical Standards", path: "/standards",
    title: "Physical Standards: Height, Chest and Run Time by Exam",
    description: "Height, chest and running standards for Army, Navy, Air Force, SSC GD, Odisha Police and railway exams, with a calculator to check your own numbers." },
  { key: "training-centres", label: "Training Centres", path: "/training-centres",
    title: "Training Centres After Selection: INS Chilka, CAPF, Odisha Police",
    description: "Where recruits train after selection, from INS Chilka in Odisha to CAPF recruit training centres and Odisha Police training, and how long training runs." },
  { key: "courses", label: "Courses", path: "/courses",
    title: "Courses: Defence, Police and CAPF, Bank, Railway and SSC Batches",
    description: "Batches at Samantroy Academy, Brahmapur: Defence Careers (NDA, CDS, SSR, MR, X and Y), Police and CAPF (SSC GD, Odisha Police, SI), and Bank, Railway and SSC." },
  { key: "eligibility", label: "Eligibility Finder", path: "/eligibility",
    title: "Eligibility Finder: Which Defence and Government Exams Can I Apply For?",
    description: "Enter your age, education and height to see every exam you qualify for. Arts and Commerce students can apply for Air Force Y, Navy MR, Army GD and SSC GD." },
  { key: "mock-tests", label: "Free Mock Tests", path: "/mock-tests",
    title: "Free Mock Tests for Army, Navy, SSC GD, Railway and Odisha Police",
    description: "Timed mock questions on the real exam pattern with negative marking, instant score and explanations. Free, no sign-up, from Samantroy Academy." },
  { key: "resources", label: "Resources", path: "/resources",
    title: "Free Notes, Syllabus PDFs, Current Affairs and Previous Papers",
    description: "Free study material from Samantroy Academy: syllabus PDFs, previous papers, weekly current affairs and video lessons, sorted by exam." },
  { key: "gallery", label: "Gallery", path: "/gallery",
    title: "Results Gallery: Samantroy Academy Selection Posters",
    description: "Result posters and selections from Samantroy Academy, Brahmapur: Indian Navy, Air Force, Army, CAPF, Bank, OSSC and OSSSC, year after year." },
  { key: "selected", label: "Wall of Selection", path: "/selected",
    title: "Wall of Selection: Selected Candidates from Samantroy Academy",
    description: "Selected candidates from Samantroy Academy, Brahmapur (Ganjam): Indian Navy, Army, Air Force, BSF, CRPF, CISF, ITBP, SSB, Odisha Police, Bank and OSSC." },
  { key: "blog", label: "Blog", path: "/blog",
    title: "Blog: Notifications, Strategy and Physical Training",
    description: "Recruitment notifications, preparation plans and physical training advice for defence, police and government job aspirants in Odisha." },
  { key: "testimonials", label: "Testimonials", path: "/testimonials",
    title: "Testimonials from Selected Aspirants",
    description: "What changed for Samantroy Academy aspirants between joining and selection, in their own words." },
  { key: "contact", label: "Contact", path: "/contact",
    title: "Contact Samantroy Academy, Brahmapur: Address and Phone",
    description: "Samantroy Academy, Gosaninuagaon, Sishu Mandir Road, 300 m from Brahmapur railway station, Ganjam, Odisha 760003. Call 98610 77371 or 90906 99770." },
];

export const getSeoPage = (key: string) => SEO_PAGES.find((p) => p.key === key);
