/** SEO defaults per page (client-safe plain data). Overridable in Admin -> SEO. */
export type SeoPage = { key: string; label: string; path: string; absolute?: boolean; title: string; description: string };

export const SEO_PAGES: SeoPage[] = [
  { key: "home", label: "Home", path: "/", absolute: true,
    title: "Samantroy Academy | Agniveer, SSC GD, Odisha Police Coaching in Odisha",
    description: "Defence and government job coaching in Odisha. Written exam, physical test and medical, trained together for Agniveer, Navy SSR and MR, Airman X and Y, SSC GD, Odisha Police and Railways." },
  { key: "about", label: "About", path: "/about",
    title: "About Samantroy Academy",
    description: "A coaching academy in Odisha that trains the written exam and the physical test together, with a real ground on campus and timed runs every morning." },
  { key: "recruitment-process", label: "Recruitment Process", path: "/recruitment-process",
    title: "Recruitment Process: Application to Joining in Seven Stages",
    description: "How Agniveer, SSC GD, Odisha Police and Railway recruitment works: application, written exam, PST, PET, document verification, medical and merit list." },
  { key: "exams", label: "Exams", path: "/exams",
    title: "Defence and Government Exams After 10th, 12th and Graduation",
    description: "Every exam we prepare for: Army Agniveer, Navy SSR and MR, Airman X and Y, SSC GD, CAPF, Odisha Police, RRB Group D, NTPC, RPF and SSC." },
  { key: "standards", label: "Physical Standards", path: "/standards",
    title: "Physical Standards: Height, Chest and Run Time by Exam",
    description: "Height, chest and physical test standards for Agniveer, SSC GD, Navy, Air Force, Odisha Police, RPF and RRB Group D, with a calculator to check your numbers." },
  { key: "training-centres", label: "Training Centres", path: "/training-centres",
    title: "Training Centres After Selection: INS Chilka, CAPF, Odisha Police",
    description: "Where recruits train after selection, from INS Chilka in Odisha to CAPF recruit training centres and Odisha Police training, and how long training runs." },
  { key: "courses", label: "Courses", path: "/courses",
    title: "Courses: Complete Selection, Written and Physical Training Batches",
    description: "Batches for the written exam, the physical test or both. Daily ground training, weekly CBT mocks and medical pre-checks at our Odisha campus." },
  { key: "eligibility", label: "Eligibility Finder", path: "/eligibility",
    title: "Eligibility Finder: Which Defence and Police Exams Can I Apply For?",
    description: "Enter your age, education, height and category to see every exam you qualify for, and the ones you are close to." },
  { key: "mock-tests", label: "Free Mock Tests", path: "/mock-tests",
    title: "Free Mock Tests for Agniveer, SSC GD, Railways and Odisha Police",
    description: "Timed mock questions on the real pattern with negative marking, instant score and explanations. Free, no sign-up." },
  { key: "resources", label: "Resources", path: "/resources",
    title: "Free Notes, Syllabus PDFs and Previous Papers",
    description: "Download free study material from Samantroy Academy: syllabus PDFs, previous papers and video lessons, sorted by exam." },
  { key: "gallery", label: "Gallery", path: "/gallery",
    title: "Gallery: Ground Training and Results",
    description: "Photos from the ground, the classroom and the aspirants who made it into uniform." },
  { key: "selected", label: "Wall of Selection", path: "/selected",
    title: "Wall of Selection: Our Selected Candidates",
    description: "Every Samantroy Academy aspirant selected across the Army, Navy, Air Force, CAPF, Odisha Police and Railways." },
  { key: "blog", label: "Blog", path: "/blog",
    title: "Blog: Notifications, Strategy and Physical Training",
    description: "Exam alerts, preparation plans and physical training advice from the trainers at Samantroy Academy." },
  { key: "testimonials", label: "Testimonials", path: "/testimonials",
    title: "Testimonials from Selected Aspirants",
    description: "What changed for our aspirants between joining and selection, in their own words." },
  { key: "contact", label: "Contact", path: "/contact",
    title: "Contact: Book a Free Counselling Call",
    description: "Talk to a trainer at Samantroy Academy. We call back with the exams you qualify for and a plan to clear them." },
];

export const getSeoPage = (key: string) => SEO_PAGES.find((p) => p.key === key);
