/**
 * Generates supabase/seed/0001_catalogue.sql from the built-in data in lib/.
 *   node scripts/generate-seed.ts
 *
 * Seeds the tables the admin edits most: exams, physical standards, mock
 * questions and FAQs. Every block is idempotent: exams skip existing slugs,
 * and the other blocks only run while their table is still empty, so
 * re-running never duplicates rows or overwrites admin edits.
 *
 * Deliberately NOT seeded: selected candidates, testimonials and faculty.
 * Those must be real, so they stay empty (the site shows labelled samples
 * until the academy adds its own).
 */
import fs from "node:fs";
import path from "node:path";
import { EXAMS } from "../lib/exams.ts";
import { STANDARD_ROWS } from "../lib/standards.ts";
import { SAMPLE_QUESTIONS } from "../lib/mock-defaults.ts";
import { FAQS } from "../lib/data.ts";

const q = (v: unknown): string => {
  if (v === null || v === undefined || v === "") return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
};
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const out: string[] = [
  "-- GENERATED by scripts/generate-seed.ts. Do not edit by hand; edit lib/ and regenerate.",
  "-- Idempotent: safe to run more than once.",
  "",
  "-- Exams catalogue",
];

for (const e of EXAMS) {
  out.push(
    `insert into public.exams (slug, name, short_name, vertical, force, stage, qualification, age_min, age_max, gender, marital_status, domicile, intro, pattern, syllabus, salary, stages, notification_month, exam_month, official_url, banner_path, sort_order, published)
values (${[e.slug, e.name, e.short_name, e.vertical, e.force, e.stage, e.qualification, e.age_min, e.age_max, e.gender, e.marital_status, e.domicile, e.intro, e.pattern, e.syllabus, e.salary].map(q).join(", ")}, ${j(e.stages)}, ${[e.notification_month, e.exam_month, e.official_url, e.banner_path, e.sort_order].map(q).join(", ")}, true)
on conflict (slug) do nothing;`,
  );
}

out.push("", "-- Physical standards (only while the table is empty). Indicative: verify every cycle.");
out.push("do $seed$ begin", "if not exists (select 1 from public.physical_standards) then");
for (const r of STANDARD_ROWS) {
  out.push(
    `  insert into public.physical_standards (exam_id, label, gender, category, region, height_cm, chest_cm, chest_expanded_cm, weight_kg, run_distance_m, run_time, long_jump, high_jump, beam_pullups, ditch, zigzag, vision, notes, sort_order, published)
  select id, ${[r.label, r.gender, r.category, r.region, r.height_cm, r.chest_cm, r.chest_expanded_cm, r.weight_kg, r.run_distance_m, r.run_time, r.long_jump, r.high_jump, r.beam_pullups, r.ditch, r.zigzag, r.vision, r.notes, r.sort_order ?? 0].map(q).join(", ")}, true
  from public.exams where slug = ${q(r.exam_slug)};`,
  );
}
out.push("end if;", "end $seed$;");

out.push("", "-- Mock questions (only while the table is empty)");
out.push("do $seed$ begin", "if not exists (select 1 from public.mock_questions) then");
SAMPLE_QUESTIONS.forEach((m, i) => {
  out.push(
    `  insert into public.mock_questions (type, subject, question, options, answer, explanation, difficulty, marks, negative_marks, sort_order, published)
  values (${q(m.type)}, ${q(m.subject)}, ${q(m.question)}, ${j(m.options)}, ${m.answer}, ${q(m.explanation)}, ${q(m.difficulty)}, ${m.marks}, ${m.negative_marks}, ${i}, true);`,
  );
});
out.push("end if;", "end $seed$;");

out.push("", "-- FAQs (only while the table is empty)");
out.push("do $seed$ begin", "if not exists (select 1 from public.faqs) then");
FAQS.forEach((f, i) => {
  out.push(`  insert into public.faqs (question, answer, sort_order, published) values (${q(f.q)}, ${q(f.a)}, ${i}, true);`);
});
out.push("end if;", "end $seed$;", "");

const file = path.join(import.meta.dirname, "..", "supabase", "seed", "0001_catalogue.sql");
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, out.join("\n"));
console.log(`wrote ${file} (${EXAMS.length} exams, ${STANDARD_ROWS.length} standards, ${SAMPLE_QUESTIONS.length} questions, ${FAQS.length} faqs)`);
